# Dockerfile for local development
FROM node:20.10.0-alpine3.17

ENV DOCKER_BUILDKIT=1

# 1. Build time environment

ARG REACT_APP_NODE_BACKEND_URI
ENV REACT_APP_NODE_BACKEND_URI=$REACT_APP_NODE_BACKEND_URI

WORKDIR /app

COPY . . 
RUN npm ci -s

ENV NODE_ENV=development

EXPOSE 3000

ENTRYPOINT ["npm", "run", "start"]
